src/03.Presentation/HW21.Presentation.RezorPages/Pages/Comment/Index.cshtml.cs
using HW21.Domain.Core.Contracts.AppService;
using HW21.Domain.Core.Dtos.Comment;
using HW21.Domain.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HW21.Presentation.RezorPages.Pages.Comment
{
    public class IndexModel(ICommentAppService commentApp) : PageModel
    {
        public List<GetCommentDto> Comments { get; set; } 
        public void OnGet(int postId)
        {
            Comments = commentApp.GetComments(postId);
           
        }

        public IActionResult OnGetReject(int commentId, int postId) {

            var result = commentApp.SetCommentStatus(commentId, Domain.Core.Enums.CommentStatus.Rejected);

            return RedirectToPage("/Comment/Index", new {postId});
        }
        public IActionResult OnGetAccept(int commentId, int postId)
        {
            var result = commentApp.SetCommentStatus(commentId, Domain.Core.Enums.CommentStatus.Accepted);
            return RedirectToPage("/Comment/Index", new {postId });
        }
    }
}

src/03.Presentation/HW21.Presentation.RezorPages/Pages/Comment/Index.cshtml
@page
@using HW21.Domain.Core.Enums
@model HW21.Presentation.RezorPages.Pages.Comment.IndexModel
@{
}
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/postAndComment.css">
    
</head>
<body>
    <div class="container">
        
        <div class="comment-box">
            <div class="comments-list">
                <h4>لیست کامنت‌ها</h4>

                @if (Model.Comments.Count != 0)
                {
                    @foreach (var comment in Model.Comments)
                    {
                        <div class="comment">
                            <div class="comment-header">
                                <span class="fullname">@comment.FirstName @comment.LastName</span>
                                <span class="email">@comment.Email</span>
                                <span class="rate">Rate: @comment.Rate/5</span>
                                
                            </div>
                            <p class="message">@comment.Text</p>
                            <div class="comment-status">
                                @Html.Raw(GetStatusBadge(comment.Status))
                                @if (comment.Status == CommentStatus.Rejected || comment.Status == CommentStatus.Pending)
                                {
                                    <a asp-route-commentId="@comment.Id" asp-route-postId="@comment.PostId" asp-page-handler="Accept"><button class="approve-btn">✔ تایید</button></a>
                                }
                                else
                                {
                                    <a asp-route-commentId="@comment.Id" asp-route-postId="@comment.PostId" asp-page-handler="Reject"><button class='reject-btn'>❌ عدم تایید</button></a>
                                }
                            </div>
                        </div>
                    }
                }
                else
                {
                    <p style="color: red;">نظری وجود ندارد</p>
                }

            </div>
        </div>
    </div>
</body>
</html>
@functions {

    public string GetStatusBadge(CommentStatus status)
    {
        return status switch
        {
            CommentStatus.Accepted => "<span class='status approved'>✔ تایید شده</span>",
            CommentStatus.Rejected => "<span class='status rejected'>❌ رد شده</span>",
            _ => "<span class='status pending'>⏳ در انتظار تایید</span>"
        };
    }

    
}